// booksData.js

import { useState } from "react";

 
// this is dummy data generated by AI. 

const booksData = [
  // ===== Fiction =====
  {
    id: 1,
    title: "The Silent Observer",
    author: "Ava Thompson",
    category: "Fiction",
    year: 2019,
    rating: 4.3,
    shortDesc: "A deep dive into human emotions and unspoken words.",
    longDesc:
      "Set in a quiet coastal town, 'The Silent Observer' explores the life of an introverted painter who discovers the stories of strangers through her art. As she paints, imagination and reality blur, revealing secrets that change her forever.",
    image:
      "https://images.unsplash.com/photo-1524995997946-a1c2e315a42f?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 2,
    title: "Shadows and Daisies",
    author: "Clara Ellis",
    category: "Fiction",
    year: 2021,
    rating: 4.4,
    shortDesc: "A bittersweet story about love and loss.",
    longDesc:
      "In a small town divided by secrets, a young woman learns to embrace love and forgiveness after uncovering her family's hidden past.",
    image:
      "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 3,
    title: "The Lighthouse Keeper",
    author: "Samuel Brooks",
    category: "Fiction",
    year: 2020,
    rating: 4.5,
    shortDesc: "A lonely keeper discovers purpose through an unlikely friendship.",
    longDesc:
      "Amid the raging waves, a reclusive lighthouse keeper befriends a stranded sailor, leading to revelations that transform both their lives.",
    image:
      "https://images.unsplash.com/photo-1483794344563-d27a8d18014e?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Sci-Fi =====
  {
    id: 4,
    title: "Beyond the Stars",
    author: "Ethan Clark",
    category: "Sci-Fi",
    year: 2021,
    rating: 4.8,
    shortDesc: "An interstellar adventure across time and consciousness.",
    longDesc:
      "In 2290, Captain Aiden Ross and his crew explore a wormhole to a new galaxy. What begins as a voyage turns into a battle for survival.",
    image:
      "https://images.unsplash.com/photo-1581091226825-a6a2a5aee158?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 5,
    title: "The Quantum Paradox",
    author: "Noah Mitchell",
    category: "Sci-Fi",
    year: 2023,
    rating: 4.9,
    shortDesc: "A physicist’s experiment bends time itself.",
    longDesc:
      "A revolutionary device capable of rewriting history threatens to collapse the timeline when used to prevent a tragedy.",
    image:
      "https://images.unsplash.com/photo-1554475901-4538ddfbccc3?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 6,
    title: "Chronicles of the Void",
    author: "Lucas Grant",
    category: "Sci-Fi",
    year: 2023,
    rating: 4.7,
    shortDesc: "A space odyssey through wormholes and lost civilizations.",
    longDesc:
      "A breathtaking story of explorers who find a civilization lost beyond the event horizon of a black hole.",
    image:
      "https://images.unsplash.com/photo-1533750349088-cd871a92f312?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Non-Fiction =====
  {
    id: 7,
    title: "The Art of Stillness",
    author: "Lily Fernandez",
    category: "Non-Fiction",
    year: 2018,
    rating: 4.5,
    shortDesc: "A guide to finding peace in a restless world.",
    longDesc:
      "In a world obsessed with noise, this book brings you back to stillness. It shares practical wisdom to cultivate inner peace.",
    image:
      "https://images.unsplash.com/photo-1509021436665-8f07dbf5bf1d?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 8,
    title: "Roots of Wisdom",
    author: "Dr. Karen Fields",
    category: "Non-Fiction",
    year: 2016,
    rating: 4.6,
    shortDesc: "Ancient philosophy meets modern life lessons.",
    longDesc:
      "An exploration of ancient wisdom and how it can guide us in today’s chaotic, fast-paced world.",
    image:
      "https://images.unsplash.com/photo-1516979187457-637abb4f9353?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 9,
    title: "Urban Jungle",
    author: "Marcus Ray",
    category: "Non-Fiction",
    year: 2023,
    rating: 4.3,
    shortDesc: "Exploring the hidden ecosystems within cities.",
    longDesc:
      "An ecological perspective on how urban landscapes foster biodiversity — from rooftop gardens to subway microbes.",
    image:
      "https://images.unsplash.com/photo-1469474968028-56623f02e42e?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Mystery =====
  {
    id: 10,
    title: "Echoes of Tomorrow",
    author: "Daniel Reed",
    category: "Mystery",
    year: 2020,
    rating: 4.1,
    shortDesc: "A detective unravels a case that challenges reality itself.",
    longDesc:
      "Detective Morgan Chase is haunted by visions of crimes that haven’t happened yet, leading to a chilling discovery.",
    image:
      "https://images.unsplash.com/photo-1512820790803-83ca734da794?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 11,
    title: "The Forgotten Key",
    author: "Mila Knight",
    category: "Mystery",
    year: 2019,
    rating: 4.5,
    shortDesc: "A cryptic key holds the secret to a missing heirloom.",
    longDesc:
      "A small-town librarian uncovers a century-old secret after discovering a mysterious key in an old novel.",
    image:
      "https://images.unsplash.com/photo-1507842217343-583bb7270b66?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 12,
    title: "Silent Testimony",
    author: "Ryan Blake",
    category: "Mystery",
    year: 2022,
    rating: 4.6,
    shortDesc: "A lawyer’s case unravels her own dark past.",
    longDesc:
      "When a defense attorney defends a man accused of murder, she realizes the evidence ties back to her childhood trauma.",
    image:
      "https://images.unsplash.com/photo-1522226764516-4e42f12d8f78?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Education =====
  {
    id: 13,
    title: "Cognitive Horizons",
    author: "Dr. Mia Kapoor",
    category: "Education",
    year: 2022,
    rating: 4.7,
    shortDesc: "Exploring the future of human intelligence and AI.",
    longDesc:
      "Dr. Kapoor explores how human cognition and artificial intelligence intertwine to shape the future of education and creativity.",
    image:
      "https://images.unsplash.com/photo-1581093588401-22e8c1b1d8d1?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 14,
    title: "Mind Over Machine",
    author: "Dr. Elena Yu",
    category: "Education",
    year: 2021,
    rating: 4.9,
    shortDesc: "A revolutionary approach to human-AI collaboration.",
    longDesc:
      "A compelling analysis of how education systems must evolve to empower humans in the age of intelligent machines.",
    image:
      "https://images.unsplash.com/photo-1488590528505-98d2b5aba04b?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 15,
    title: "Mindful Horizons",
    author: "Lena Carter",
    category: "Education",
    year: 2018,
    rating: 4.5,
    shortDesc: "Reinventing classrooms for future generations.",
    longDesc:
      "A visionary outlook on modern education systems that nurture creativity, emotional intelligence, and self-awareness.",
    image:
      "https://images.unsplash.com/photo-1519389950473-47ba0277781c?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Poetry =====
  {
    id: 16,
    title: "Ocean Whispers",
    author: "Nora Grey",
    category: "Poetry",
    year: 2017,
    rating: 4.4,
    shortDesc: "A lyrical collection celebrating love and loss by the sea.",
    longDesc:
      "A compilation of poems weaving longing, nostalgia, and rebirth — painting the ocean as both healer and destroyer.",
    image:
      "https://images.unsplash.com/photo-1473187983305-f615310e7daa?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 17,
    title: "Sea of Dreams",
    author: "Amelia Flores",
    category: "Poetry",
    year: 2016,
    rating: 4.6,
    shortDesc: "A poetic dive into dreams and forgotten love.",
    longDesc:
      "Through soft, melancholic verses, this collection explores the fragility of dreams and the persistence of love.",
    image:
      "https://images.unsplash.com/photo-1520523839897-bd0b52f945a0?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 18,
    title: "Whispers of Dawn",
    author: "Kiran Mehta",
    category: "Poetry",
    year: 2019,
    rating: 4.3,
    shortDesc: "Poems about beginnings, endings, and everything between.",
    longDesc:
      "A soothing blend of introspection and hope, ‘Whispers of Dawn’ celebrates the beauty of change and rebirth.",
    image:
      "https://images.unsplash.com/photo-1483794344563-d27a8d18014e?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Romance =====
  {
    id: 19,
    title: "Midnight Sonata",
    author: "Sophia Lee",
    category: "Romance",
    year: 2019,
    rating: 4.2,
    shortDesc: "A love story intertwined with music and destiny.",
    longDesc:
      "Two pianists from rival schools fall in love during a competition. Their melodies become the language of their souls.",
    image:
      "https://images.unsplash.com/photo-1497032628192-86f99bcd76bc?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 20,
    title: "Paper Planes",
    author: "Ella Brooks",
    category: "Romance",
    year: 2019,
    rating: 4.2,
    shortDesc: "A childhood love story rekindled after a decade.",
    longDesc:
      "When two childhood friends reunite through letters, they rediscover a love that never truly faded.",
    image:
      "https://images.unsplash.com/photo-1496307042754-b4aa456c4a2d?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 21,
    title: "Moonlit Promises",
    author: "Nina Valdez",
    category: "Romance",
    year: 2022,
    rating: 4.5,
    shortDesc: "Two strangers meet where fate and timing collide.",
    longDesc:
      "Set in Paris, two artists cross paths under moonlight, each healing from heartbreak and finding a new rhythm in love.",
    image:
      "https://images.unsplash.com/photo-1519681393784-d120267933ba?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Adventure =====
  {
    id: 22,
    title: "Winds of the North",
    author: "Elena Brooks",
    category: "Adventure",
    year: 2021,
    rating: 4.3,
    shortDesc: "An Arctic expedition turns into a fight for survival.",
    longDesc:
      "A young explorer leads her team into frozen wastelands, uncovering ancient relics and a dark secret beneath the ice.",
    image:
      "https://images.unsplash.com/photo-1476611338391-6f395a0ebc7b?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 23,
    title: "The Forgotten City",
    author: "Zane Foster",
    category: "Adventure",
    year: 2016,
    rating: 4.1,
    shortDesc: "An ancient map leads to a hidden civilization.",
    longDesc:
      "An archaeologist follows clues left by his grandfather to uncover a city lost beneath the sands of the Sahara.",
    image:
      "https://images.unsplash.com/photo-1522335789203-aabd1fc54bc9?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 24,
    title: "Broken Compass",
    author: "Tom Carter",
    category: "Adventure",
    year: 2021,
    rating: 4.5,
    shortDesc: "A lost explorer finds more than treasure.",
    longDesc:
      "Deep in the Amazon, an explorer searching for riches finds the true meaning of courage and friendship.",
    image:
      "https://images.unsplash.com/photo-1522202176988-66273c2fd55f?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Fantasy =====
  {
    id: 25,
    title: "Threads of Fate",
    author: "Hannah Scott",
    category: "Fantasy",
    year: 2018,
    rating: 4.5,
    shortDesc: "A girl discovers she can alter destiny with a single thread.",
    longDesc:
      "In a world where every person’s fate is woven by gods, one mortal finds the power to change destiny — and chaos follows.",
    image:
      "https://images.unsplash.com/photo-1473186505569-9c61870c11f9?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 26,
    title: "Rise of the Phoenix",
    author: "Rachel Monroe",
    category: "Fantasy",
    year: 2019,
    rating: 4.8,
    shortDesc: "A warrior reborn from ashes to reclaim her destiny.",
    longDesc:
      "In a kingdom torn by war, a fallen knight is resurrected by a mythical phoenix to lead the rebellion.",
    image:
      "https://images.unsplash.com/photo-1544717302-de2939b7ef71?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 27,
    title: "Legacy of Light",
    author: "Rina Das",
    category: "Fantasy",
    year: 2022,
    rating: 4.7,
    shortDesc: "The prophecy of the chosen bearer of light.",
    longDesc:
      "A young orphan discovers her destiny as the guardian of a world plunged into eternal night.",
    image:
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
  },

  // ===== Self-Help =====
  {
    id: 28,
    title: "Digital Nomad Life",
    author: "Chris Parker",
    category: "Self-Help",
    year: 2022,
    rating: 4.6,
    shortDesc: "Mastering freedom and productivity on the go.",
    longDesc:
      "Practical insights on how to live, work, and thrive while traveling — balancing income, freedom, and purpose.",
    image:
      "https://images.unsplash.com/photo-1504384308090-c894fdcc538d?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 29,
    title: "Art of Letting Go",
    author: "Dr. Sofia Patel",
    category: "Self-Help",
    year: 2018,
    rating: 4.5,
    shortDesc: "Learn the beauty of detachment and peace.",
    longDesc:
      "A mindful guide to breaking free from overthinking and emotional baggage to live a peaceful life.",
    image:
      "https://images.unsplash.com/photo-1473186505569-9c61870c11f9?auto=format&fit=crop&w=400&q=80",
  },
  {
    id: 30,
    title: "Dream Architects",
    author: "Victor Hayes",
    category: "Self-Help",
    year: 2020,
    rating: 4.4,
    shortDesc: "Designing your ideal life through imagination.",
    longDesc:
      "An inspiring guide on shaping destiny by aligning thought, vision, and disciplined action.",
    image:
      "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?auto=format&fit=crop&w=400&q=80",
  },
];

 
export default booksData
